repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^src/test/.*|^test/.*|\.py$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^src/test/.*|^test/.*|\.py$

  - repo: local
    hooks:
      - id: mvn-spotless-apply
        name: Maven Spotless Apply
        entry: mvn -B -ntp spotless:apply
        language: system
        files: '\.(java|md)$'
        pass_filenames: false

      - id: mvn-checkstyle
        name: Maven Checkstyle (pre-push)
        entry: mvn -B -ntp checkstyle:check
        language: system
        stages: [pre-push]
        pass_filenames: false
